### ISSUE TITLE
Odoo-ls not killed automatically when I kill VS Code

### ISSUE THREAD

**Issue by remyAuneor** [odoo/odoo-ls#78] opened 2023-11-20 16:23 UTC
**Your setup**
Version: 0.2.1 &0.2.2
Operating System: Ubuntu 22.04 and i3 desktop manager
IDE and/or Integration tool (for example: Vscode - official extension): Vscode - official extension

**Describe the bug**
When I kill VS Code (Ctrl+q) the extension process is not killed automatically, annoying when I am working on multiples instances of VS code and each odoo-ls server is taking 1.8Go of RAM memory

**To Reproduce**
Steps to reproduce the behavior:*
Kill VS Code with Ctrl+q and check in the monitor that the instances of odoo-ls is still here 

**Expected behavior**
It should be killed at the same time as VS Code ?

**Comment by fda-odoo** [comment] 2023-11-20 16:39
Hello @remyAuneor , thank you for your report.
We are aware that the server process is sometimes reluctant to close properly when you quit vscode or uninstall the extension. We are actually working on it and a fix should come in the next days/week.

Regarding the ram usage, unfortunately the extension is actually loading the whole project and it can take some space in RAM. We want to improve that too, but adding cache levels and reducing memory usage is not the priority of this version, we will come back on it when the extension will be considered as stable and have enough features first. I won't give an ETA now, but know that we want to reduce the ram usage too and keep that in mind

**Comment by yao-big** [comment] 2023-11-21 10:46
Can I automatically detect the source code location of ODOO?

Configure yourself for the rest

The odoo ide plugin can detect

**Comment by fda-odoo** [comment] 2024-12-19 14:11
I close this issue as now the Rust version is listening for the vscode PID, and automatically close if vscode close, even if no exit signal was received. As it was not the case in 0.2.4, I assume the problem is solved for now

**Closed by fda-odoo** 2024-12-19 14:11 UTC
Labels: bug
